#!/bin/bash

# Build script for Node.js hello-world-node.js demo
# Concatenates existing source files to build the standalone demo

set -e  # Exit on any error

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Building Node.js hello-world demo..."

# Project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Define paths
SRC_DIR="$PROJECT_ROOT/src"
LIB_DIR="$PROJECT_ROOT/lib"
OUTPUT_DIR="$PROJECT_ROOT/examples/node/dist"
OUTPUT_FILE="$OUTPUT_DIR/hello-world.bundle.js"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Project root: $PROJECT_ROOT"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Output file: $OUTPUT_FILE"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Verify all source files exist
FILES_TO_CHECK=(
  "$SRC_DIR/node/canvas-mock.js"
  "$SRC_DIR/node/font-loader-node.js"
  "$SRC_DIR/core/StatusCode.js"
  "$SRC_DIR/core/FontProperties.js"
  "$SRC_DIR/core/TextProperties.js"
  "$SRC_DIR/core/FontMetrics.js"
  "$SRC_DIR/minification/MetricsExpander.js"
  "$SRC_DIR/core/AtlasPositioning.js"
  "$SRC_DIR/core/AtlasData.js"
  "$SRC_DIR/minification/AtlasExpander.js"
  "$LIB_DIR/QOIDecode.js"
  "$LIB_DIR/PngEncodingOptions.js"
  "$LIB_DIR/PngEncoder.js"
  "$SRC_DIR/core/AtlasDataStore.js"
  "$SRC_DIR/core/FontMetricsStore.js"
  "$SRC_DIR/core/BitmapText.js"
  "$SRC_DIR/node/hello-world-main.js"
)

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Checking source files..."
for file in "${FILES_TO_CHECK[@]}"; do
  if [[ ! -f "$file" ]]; then
    echo "ERROR: Required source file not found: $file"
    exit 1
  fi
done
echo "[$(date '+%Y-%m-%d %H:%M:%S')] All source files found ✓"

# Start building the output file
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Concatenating files..."

cat > "$OUTPUT_FILE" << 'EOF'
#!/usr/bin/env node

/**
 * ⚠️  THIS IS A BUNDLED/BUILT FILE - DO NOT EDIT ⚠️
 * 
 * BitmapText.js Node.js Demo - Hello World Single Size
 * 
 * This file is automatically generated by concatenating multiple source files.
 * 
 * Source files:
 *   - src/node/hello-world-main.js (main demo logic)
 *   - src/core/BitmapText.js (core rendering)
 *   - src/core/AtlasDataStore.js (atlas data storage)
 *   - src/node/canvas-mock.js (Canvas implementation)
 *   - lib/QOIDecode.js, lib/PngEncoder.js (image handling)
 * 
 * To modify this demo:
 *   1. Edit source files in src/node/ and related directories
 *   2. Run: ./scripts/build-node-demo.sh
 * 
 * Usage:
 *   node examples/node/dist/hello-world.bundle.js
 * 
 * Output:
 *   hello-world-output.png (in current directory)
 * 
 * Generated by: scripts/build-node-demo.sh
 * Bundle size: ~54KB standalone executable with no dependencies
 */

// ============================================================================
EOF

# Concatenate Canvas mock
echo "// MINIMAL CANVAS MOCK - Only what BitmapText.js needs" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
tail -n +2 "$SRC_DIR/node/canvas-mock.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate FontLoader for Node.js (skip require statements to avoid duplicates)
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// FONTLOADER NODE.JS IMPLEMENTATION" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
tail -n +18 "$SRC_DIR/node/font-loader-node.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate StatusCode class (MUST BE FIRST before BitmapText)
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// STATUS CODE CONSTANTS AND HELPERS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/StatusCode.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate FontProperties class
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// FONT PROPERTIES CLASS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/FontProperties.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate TextProperties class
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// TEXT PROPERTIES CLASS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/TextProperties.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate FontMetrics class
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// FONT METRICS CLASS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/FontMetrics.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate expansion utility
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// EXPANSION UTILITY - MetricsExpander.js" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/minification/MetricsExpander.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate AtlasPositioning class
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// ATLAS POSITIONING CLASS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/AtlasPositioning.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate AtlasData class
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// ATLAS DATA CLASS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/AtlasData.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate AtlasExpander
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// ATLAS EXPANDER UTILITY" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/minification/AtlasExpander.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate QOI decoder
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// QOI DECODER LIBRARY" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$LIB_DIR/QOIDecode.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate PNG encoding options
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// PNG ENCODING OPTIONS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$LIB_DIR/PngEncodingOptions.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate PNG encoder
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// PNG ENCODER" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$LIB_DIR/PngEncoder.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate AtlasDataStore
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// ATLAS DATA STORE" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/AtlasDataStore.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate FontMetricsStore
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// FONT METRICS STORE" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/FontMetricsStore.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate BitmapText
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// BITMAP TEXT RENDERER" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/BitmapText.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate main execution
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// MAIN EXECUTION - Node.js Hello World Demo" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
tail -n +2 "$SRC_DIR/node/hello-world-main.js" >> "$OUTPUT_FILE"

# Make the output file executable
chmod +x "$OUTPUT_FILE"

# Calculate file stats
FILE_SIZE=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
LINE_COUNT=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Build completed successfully! ✅"
echo ""
echo "Output: $OUTPUT_FILE"
echo "Size: $FILE_SIZE bytes"
echo "Lines: $LINE_COUNT"
echo ""
echo "To run the demo:"
echo "  cd $PROJECT_ROOT"
echo "  node examples/node/dist/hello-world.bundle.js"
echo ""
echo "To rebuild:"
echo "  ./scripts/build-node-demo.sh"