#!/bin/bash

# Build script for Node.js hello-world-multi-size-node.js demo
# Concatenates existing source files to build the standalone multi-size demo

set -e  # Exit on any error

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Building Node.js hello-world-multi-size demo..."

# Project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Define paths
SRC_DIR="$PROJECT_ROOT/src"
LIB_DIR="$PROJECT_ROOT/lib"
OUTPUT_DIR="$PROJECT_ROOT/examples/node/dist"
OUTPUT_FILE="$OUTPUT_DIR/hello-world-multi-size.bundle.js"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Project root: $PROJECT_ROOT"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Output file: $OUTPUT_FILE"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Verify all source files exist
FILES_TO_CHECK=(
  "$SRC_DIR/node/canvas-mock.js"
  "$SRC_DIR/utils/nested-properties.js"
  "$SRC_DIR/minification/MetricsExpander.js"
  "$LIB_DIR/QOIDecode.js"
  "$LIB_DIR/PngEncodingOptions.js"
  "$LIB_DIR/PngEncoder.js"
  "$SRC_DIR/core/BitmapGlyphStore.js"
  "$SRC_DIR/core/BitmapText.js"
  "$SRC_DIR/node/hello-world-multi-size-main.js"
)

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Checking source files..."
for file in "${FILES_TO_CHECK[@]}"; do
  if [[ ! -f "$file" ]]; then
    echo "ERROR: Required source file not found: $file"
    exit 1
  fi
done
echo "[$(date '+%Y-%m-%d %H:%M:%S')] All source files found ✓"

# Start building the output file
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Concatenating files..."

cat > "$OUTPUT_FILE" << 'EOF'
#!/usr/bin/env node

/**
 * ⚠️  THIS IS A BUNDLED/BUILT FILE - DO NOT EDIT ⚠️
 * 
 * BitmapText.js Node.js Demo - Hello World Multi-Size
 * 
 * This file is automatically generated by concatenating multiple source files.
 * 
 * Source files:
 *   - src/node/hello-world-multi-size-main.js (main demo logic)
 *   - src/core/BitmapText.js (core rendering)
 *   - src/core/BitmapGlyphStore.js (glyph storage)
 *   - src/node/canvas-mock.js (Canvas implementation)
 *   - lib/QOIDecode.js, lib/PngEncoder.js (image handling)
 * 
 * This demonstrates:
 * - Multi-size font loading and rendering (sizes 18, 18.5, 19)
 * - Graceful handling of missing glyph sheets (placeholder rectangles)
 * - Loading from both main directory and removed-for-testing directory
 * 
 * To modify this demo:
 *   1. Edit source files in src/node/ and related directories
 *   2. Run: ./scripts/build-node-multi-size-demo.sh
 * 
 * Usage:
 *   node examples/node/dist/hello-world-multi-size.bundle.js
 * 
 * Output:
 *   hello-world-multi-size-output.png (in current directory)
 * 
 * Generated by: scripts/build-node-multi-size-demo.sh
 * Bundle size: ~58KB standalone executable with no dependencies
 */

// ============================================================================
EOF

# Concatenate Canvas mock
echo "// MINIMAL CANVAS MOCK - Only what BitmapText.js needs" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
tail -n +2 "$SRC_DIR/node/canvas-mock.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate utility functions
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// UTILITY FUNCTIONS - nested-properties.js" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/utils/nested-properties.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate expansion utility
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// EXPANSION UTILITY - MetricsExpander.js" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/minification/MetricsExpander.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate QOI decoder
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// QOI DECODER LIBRARY" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$LIB_DIR/QOIDecode.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate PNG encoding options
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// PNG ENCODING OPTIONS" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$LIB_DIR/PngEncodingOptions.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate PNG encoder
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// PNG ENCODER" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$LIB_DIR/PngEncoder.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate BitmapGlyphStore
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// BITMAP GLYPH STORE" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/BitmapGlyphStore.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate BitmapText
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// BITMAP TEXT RENDERER" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/core/BitmapText.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate main execution (using multi-size version)
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// MAIN EXECUTION - Node.js Hello World Multi-Size Demo" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
tail -n +2 "$SRC_DIR/node/hello-world-multi-size-main.js" >> "$OUTPUT_FILE"

# Make the output file executable
chmod +x "$OUTPUT_FILE"

# Calculate file stats
FILE_SIZE=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
LINE_COUNT=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Build completed successfully! ✅"
echo ""
echo "Output: $OUTPUT_FILE"
echo "Size: $FILE_SIZE bytes"
echo "Lines: $LINE_COUNT"
echo ""
echo "To run the multi-size demo:"
echo "  cd $PROJECT_ROOT"
echo "  node examples/node/dist/hello-world-multi-size.bundle.js"
echo ""
echo "To rebuild:"
echo "  ./scripts/build-node-multi-size-demo.sh"
echo ""
echo "Expected output:"
echo "  - hello-world-multi-size-output.png (400x200 canvas)"
echo "  - Three lines of text at sizes 18, 18.5, and 19"
echo "  - Missing glyph sheets will show placeholder rectangles"