#!/bin/bash

# Build script for BitmapText.js runtime bundles
# Concatenates runtime source files and minifies with terser
#
# Usage:
#   ./scripts/build-runtime-bundle.sh [--browser|--node|--all]
#
# Options:
#   --browser  Build browser bundle only (default)
#   --node     Build Node.js bundle only
#   --all      Build both bundles

set -e  # Exit on any error

# Parse arguments
BUILD_BROWSER=true
BUILD_NODE=false

if [[ $# -gt 0 ]]; then
  case "$1" in
    --browser)
      BUILD_BROWSER=true
      BUILD_NODE=false
      ;;
    --node)
      BUILD_BROWSER=false
      BUILD_NODE=true
      ;;
    --all)
      BUILD_BROWSER=true
      BUILD_NODE=true
      ;;
    --help)
      echo "Usage: $0 [--browser|--node|--all]"
      echo ""
      echo "Options:"
      echo "  --browser  Build browser bundle only (default)"
      echo "  --node     Build Node.js bundle only"
      echo "  --all      Build both bundles"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Building BitmapText.js runtime bundles..."

# Project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Define paths
SRC_DIR="$PROJECT_ROOT/src"
LIB_DIR="$PROJECT_ROOT/lib"
OUTPUT_DIR="$PROJECT_ROOT/dist"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Project root: $PROJECT_ROOT"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Common runtime files (used by both browser and node)
COMMON_FILES=(
  "$SRC_DIR/runtime/StatusCode.js"
  "$SRC_DIR/runtime/FontProperties.js"
  "$SRC_DIR/runtime/TextProperties.js"
  "$SRC_DIR/runtime/FontMetrics.js"
  "$SRC_DIR/runtime/InterpolatedFontMetrics.js"
  "$SRC_DIR/runtime/CharacterSets.js"
  "$SRC_DIR/runtime/BitmapText.js"
  "$SRC_DIR/builder/MetricsExpander.js"
  "$SRC_DIR/runtime/AtlasPositioning.js"
  "$SRC_DIR/runtime/AtlasImage.js"
  "$SRC_DIR/runtime/AtlasData.js"
  "$SRC_DIR/builder/AtlasReconstructionUtils.js"
  "$SRC_DIR/utils/AtlasCellDimensions.js"
  "$SRC_DIR/runtime/TightAtlasReconstructor.js"
  "$SRC_DIR/runtime/AtlasDataStore.js"
  "$SRC_DIR/runtime/FontMetricsStore.js"
  "$SRC_DIR/runtime/FontManifest.js"
  "$SRC_DIR/runtime/FontLoaderBase.js"
)

# Browser-specific files
BROWSER_SPECIFIC_FILES=(
  "$SRC_DIR/platform/FontLoader-browser.js"
)

# Node-specific files
NODE_SPECIFIC_FILES=(
  "$LIB_DIR/QOIDecode.js"
  "$SRC_DIR/platform/FontLoader-node.js"
)

# Function to verify files exist
verify_files() {
  local files=("$@")
  for file in "${files[@]}"; do
    if [[ ! -f "$file" ]]; then
      echo "ERROR: Required source file not found: $file"
      exit 1
    fi
  done
}

# Function to add file header
add_file_header() {
  local output_file="$1"
  local filename="$2"
  local description="$3"

  echo "// ============================================================================" >> "$output_file"
  echo "// $filename - $description" >> "$output_file"
  echo "// ============================================================================" >> "$output_file"
  echo "" >> "$output_file"
}

# Function to build bundle
build_bundle() {
  local bundle_name="$1"
  local output_file="$2"
  local files=("${@:3}")

  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Building $bundle_name bundle..."
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Output: $output_file"

  # Verify all files exist
  verify_files "${files[@]}"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] All source files found ✓"

  # Create bundle header
  cat > "$output_file" << 'EOF'
/**
 * BitmapText.js - Runtime Bundle
 *
 * Pixel-perfect bitmap text rendering for HTML5 Canvas
 *
 * ⚠️  DO NOT EDIT - Generated by scripts/build-runtime-bundle.sh
 *
 * This bundle contains the complete BitmapText.js runtime for rendering
 * pre-generated bitmap fonts. It does NOT include font generation tools.
 *
 * Bundle Contents:
 *   - StatusCode (status reporting)
 *   - FontProperties/TextProperties (configuration)
 *   - FontMetrics (font metrics domain object)
 *   - BitmapText (core runtime with CHARACTER_SET)
 *   - MetricsExpander (minified metrics expansion)
 *   - Atlas classes (AtlasPositioning, AtlasImage, AtlasData)
 *   - TightAtlasReconstructor (runtime atlas reconstruction)
 *   - FontLoader (font loading with platform detection)
 *   - Atlas/Metrics stores (data storage)
 *
 * Usage (Browser):
 *   <script src="dist/bitmaptext.min.js"></script>
 *   <script>
 *     const fontProps = new FontProperties(1, "Arial", "normal", "normal", 19);
 *     await BitmapText.loadFont(fontProps.idString);
 *     BitmapText.drawTextFromAtlas(ctx, "Hello", 10, 50, fontProps);
 *   </script>
 *
 * Usage (Node.js):
 *   import { createCanvas } from 'node-canvas';  // or 'skia-canvas'
 *   import './dist/bitmaptext-node.min.js';
 *
 *   BitmapText.configure({
 *     fontDirectory: './font-assets/',
 *     canvasFactory: () => createCanvas()
 *   });
 *
 *   await BitmapText.loadFont(fontProps.idString);
 *   BitmapText.drawTextFromAtlas(ctx, "Hello", 10, 50, fontProps);
 *
 * License: SEE LICENSE IN LICENSE
 */

EOF

  # Concatenate files
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Concatenating files..."

  for file in "${files[@]}"; do
    filename=$(basename "$file")
    add_file_header "$output_file" "$filename" "Source: $file"
    cat "$file" >> "$output_file"
    echo "" >> "$output_file"
  done

  # Add global exports footer for Node.js bundles
  if [[ "$bundle_name" == "Node.js" ]]; then
    cat >> "$output_file" << 'NODEJS_FOOTER'
// ============================================================================
// GLOBAL EXPORTS (Node.js)
// ============================================================================
// Expose classes globally for Node.js require() usage
if (typeof global !== 'undefined') {
  global.StatusCode = StatusCode;
  global.SUCCESS_STATUS = SUCCESS_STATUS;
  global.createErrorStatus = createErrorStatus;
  global.getStatusDescription = getStatusDescription;
  global.FontProperties = FontProperties;
  global.TextProperties = TextProperties;
  global.FontMetrics = FontMetrics;
  global.BitmapText = BitmapText;
  global.AtlasDataStore = AtlasDataStore;
  global.FontMetricsStore = FontMetricsStore;
  global.FontManifest = FontManifest;
  global.QOIDecode = QOIDecode;
}
NODEJS_FOOTER
  fi

  # Get unminified size
  local unmin_size=$(wc -c < "$output_file" | tr -d ' ')
  local unmin_kb=$((unmin_size / 1024))

  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Unminified: ${unmin_kb}KB (${unmin_size} bytes)"

  # Minify with terser
  local minified_file="${output_file%.js}.min.js"
  local sourcemap_file="$(basename "$minified_file").map"

  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Minifying with terser..."

  # Check if terser is installed
  if ! command -v terser &> /dev/null; then
    echo "ERROR: terser not found. Install with: npm install -g terser"
    exit 1
  fi

  terser "$output_file" \
    --compress passes=2 \
    --mangle \
    --output "$minified_file" \
    --source-map "url=$sourcemap_file,includeSources"

  # Get minified size
  local min_size=$(wc -c < "$minified_file" | tr -d ' ')
  local min_kb=$((min_size / 1024))
  local reduction=$((100 - (min_size * 100 / unmin_size)))

  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Minified:   ${min_kb}KB (${min_size} bytes)"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Reduction:  ${reduction}%"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ $bundle_name bundle complete!"
  echo ""
}

# Build browser bundle
if [[ "$BUILD_BROWSER" == true ]]; then
  BROWSER_FILES=("${COMMON_FILES[@]}" "${BROWSER_SPECIFIC_FILES[@]}")
  build_bundle "Browser" "$OUTPUT_DIR/bitmaptext.js" "${BROWSER_FILES[@]}"
fi

# Build node bundle
if [[ "$BUILD_NODE" == true ]]; then
  NODE_FILES=("${COMMON_FILES[@]}" "${NODE_SPECIFIC_FILES[@]}")
  build_bundle "Node.js" "$OUTPUT_DIR/bitmaptext-node.js" "${NODE_FILES[@]}"
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] ================================================"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Build completed successfully! ✅"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] ================================================"
echo ""
echo "Output directory: $OUTPUT_DIR"
echo ""

if [[ "$BUILD_BROWSER" == true ]]; then
  echo "Browser bundle:"
  echo "  - bitmaptext.js (unminified)"
  echo "  - bitmaptext.min.js (production)"
  echo "  - bitmaptext.min.js.map (source map)"
  echo ""
fi

if [[ "$BUILD_NODE" == true ]]; then
  echo "Node.js bundle:"
  echo "  - bitmaptext-node.js (unminified)"
  echo "  - bitmaptext-node.min.js (production)"
  echo "  - bitmaptext-node.min.js.map (source map)"
  echo ""
fi

echo "To use in browser:"
echo "  <script src=\"dist/bitmaptext.min.js\"></script>"
echo ""
echo "To use in Node.js:"
echo "  import { createCanvas } from 'node-canvas';"
echo "  import './dist/bitmaptext-node.min.js';"
echo "  BitmapText.configure({ canvasFactory: () => createCanvas() });"
echo ""
echo "See dist/README.md for complete documentation"
