#!/bin/bash

# Build script for metrics minifier tool
# Concatenates existing source files to build a standalone Node.js script
# that minifies full metrics files and performs roundtrip verification

set -e  # Exit on any error

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Building metrics minifier tool..."

# Project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Define paths
SRC_DIR="$PROJECT_ROOT/src"
OUTPUT_FILE="$PROJECT_ROOT/tools/minify-metrics.js"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Project root: $PROJECT_ROOT"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Output file: $OUTPUT_FILE"

# Verify all source files exist
FILES_TO_CHECK=(
  "$SRC_DIR/runtime/CHARACTER_SET.js"
  "$SRC_DIR/runtime/FontMetrics.js"
  "$SRC_DIR/builder/MetricsMinifier.js"
  "$SRC_DIR/builder/MetricsExpander.js"
  "$SRC_DIR/utils/deep-equal.js"
)

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Checking source files..."
for file in "${FILES_TO_CHECK[@]}"; do
  if [[ ! -f "$file" ]]; then
    echo "ERROR: Required source file not found: $file"
    exit 1
  fi
done
echo "[$(date '+%Y-%m-%d %H:%M:%S')] All source files found ✓"

# Start building the output file
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Concatenating files..."

cat > "$OUTPUT_FILE" << 'EOF'
#!/usr/bin/env node

/**
 * ⚠️  THIS IS A BUNDLED/BUILT FILE - DO NOT EDIT ⚠️
 *
 * Metrics Minifier - Processes full metrics files and outputs minified versions
 *
 * This file is automatically generated by concatenating multiple source files.
 * It uses the EXACT SAME CODE as the font-assets-builder page for minification
 * and roundtrip verification, ensuring identical behavior.
 *
 * Source files concatenated (in dependency order):
 *   1. src/runtime/CHARACTER_SET.js - Character set constant (204 chars)
 *   2. src/runtime/FontMetrics.js - FontMetrics class
 *   3. src/builder/MetricsMinifier.js - Minification logic
 *   4. src/builder/MetricsExpander.js - Expansion for roundtrip
 *   5. src/utils/deep-equal.js - Deep equality comparison
 *
 * Purpose:
 *   - Find all *-full.js files in font-assets/
 *   - Extract full metricsData from each file
 *   - Run MetricsMinifier.minifyWithVerification() (includes roundtrip check)
 *   - Output minified .js files as *-full-minified.js
 *   - Report statistics and verification results
 *
 * Usage:
 *   ./tools/minify-metrics.js [options]
 *   node tools/minify-metrics.js [options]
 *
 * Options:
 *   --verify-exact    Compare output with production metrics-*.js files (byte-for-byte)
 *   --help, -h        Show this help message
 *
 * Input:  font-assets/metrics-...-full.js (full metrics from font-assets-builder)
 * Output: font-assets/metrics-...-full-minified.js (minified .js files)
 *
 * To rebuild this tool:
 *   ./scripts/build-metrics-minifier.sh
 *
 * Generated by: scripts/build-metrics-minifier.sh
 */

// ============================================================================
// NODE.JS BUILT-IN MODULES
// ============================================================================

const fs = require('fs');
const path = require('path');

// ============================================================================
// COMMAND-LINE ARGUMENT PARSING
// ============================================================================

const args = process.argv.slice(2);
const options = {
  verifyExact: args.includes('--verify-exact'),
  help: args.includes('--help') || args.includes('-h')
};

if (options.help) {
  console.log(`
Metrics Minifier - Test minification strategies on full metrics files

Usage:
  ./tools/minify-metrics.js [options]
  node tools/minify-metrics.js [options]

Options:
  --verify-exact    Compare output with production metrics-*.js files
                    Performs byte-for-byte comparison to verify node script
                    produces identical output to browser font-assets-builder
                    (useful for validating the tool, not for testing new strategies)

  --help, -h        Show this help message

Description:
  Processes all *-full.js files in font-assets/ directory:
  1. Extracts full metricsData from each file
  2. Runs MetricsMinifier.minifyWithVerification() (includes roundtrip check)
  3. Outputs minified .js files as *-full-minified.js
  4. Reports statistics and verification results

  The tool uses the EXACT same minification code as the browser
  font-assets-builder page, ensuring identical behavior.

Prerequisites:
  Generate *-full.js files first:
  1. Open public/font-assets-builder.html in browser
  2. Configure font settings
  3. Check "Include non-minified metrics files"
  4. Click "Download font assets"
  5. Extract fontAssets.zip to font-assets/

Examples:
  # Standard usage (no comparison with production files)
  ./tools/minify-metrics.js

  # Verify output matches production files exactly
  ./tools/minify-metrics.js --verify-exact

Development Workflow:
  # Test new minification strategy
  1. Edit src/builder/MetricsMinifier.js
  2. ./scripts/build-metrics-minifier.sh
  3. ./tools/minify-metrics.js
  4. Examine *-full-minified.js output files
`);
  process.exit(0);
}

// ============================================================================
EOF

# Concatenate CHARACTER_SET (MUST BE FIRST - required by both Minifier and Expander)
echo "// CHARACTER SET CONSTANT" >> "$OUTPUT_FILE"
echo "// Required by both MetricsMinifier and MetricsExpander" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/runtime/CHARACTER_SET.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate FontMetrics (required by MetricsExpander)
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// FONT METRICS CLASS" >> "$OUTPUT_FILE"
echo "// Required by MetricsExpander for creating FontMetrics instances" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/runtime/FontMetrics.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate MetricsMinifier
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// METRICS MINIFIER" >> "$OUTPUT_FILE"
echo "// Tier 3-5 optimizations: 2D kerning, value indexing, tuplet deduplication" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/builder/MetricsMinifier.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate MetricsExpander (used by minifyWithVerification for roundtrip)
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// METRICS EXPANDER" >> "$OUTPUT_FILE"
echo "// Used by MetricsMinifier.minifyWithVerification() for roundtrip checks" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/builder/MetricsExpander.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Concatenate deep-equal utility (used for verification)
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "// DEEP EQUAL UTILITY" >> "$OUTPUT_FILE"
echo "// Used by verification logic to compare original vs expanded metrics" >> "$OUTPUT_FILE"
echo "// ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
cat "$SRC_DIR/utils/deep-equal.js" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Add main script logic
cat >> "$OUTPUT_FILE" << 'EOF'
// ============================================================================
// MAIN SCRIPT LOGIC
// ============================================================================

// ============================================================================

function processFullMetricsFiles() {
  const fontAssetsDir = path.join(__dirname, '..', 'font-assets');
  const productionDir = fontAssetsDir; // Production files in same directory

  // Check if font-assets directory exists
  if (!fs.existsSync(fontAssetsDir)) {
    console.error('❌ font-assets/ directory not found');
    console.error('   Expected at:', fontAssetsDir);
    process.exit(1);
  }

  // Find all -full.js files
  const files = fs.readdirSync(fontAssetsDir).filter(f => f.endsWith('-full.js'));

  if (files.length === 0) {
    console.log('\n⚠️  No *-full.js files found in font-assets/');
    console.log('');
    console.log('To generate full metrics files:');
    console.log('  1. Open public/font-assets-builder.html in browser');
    console.log('  2. Configure your font settings');
    console.log('  3. Check "Include non-minified metrics files"');
    console.log('  4. Click "Download font assets"');
    console.log('  5. Extract fontAssets.zip to font-assets/');
    console.log('');
    process.exit(0);
  }

  console.log('\n🔬 Metrics Minification & Verification');
  console.log('═'.repeat(60));
  console.log(`Found ${files.length} full metrics file(s) to process`);
  if (options.verifyExact) {
    console.log('🔍 Exact verification: ENABLED (comparing with production files)');
  }
  console.log('');

  let successCount = 0;
  let errorCount = 0;
  const results = [];

  for (const filename of files) {
    const fullPath = path.join(fontAssetsDir, filename);

    try {
      // Read file content
      const content = fs.readFileSync(fullPath, 'utf8');

      // Extract metricsData using capture mechanism
      // The -full.js files have format (Tier 6):
      // BitmapText.r('compressedID', {...metricsData...})
      // OR legacy format:
      // BitmapText.registerMetrics('idString', {...metricsData...})
      let capturedIdString = null;
      let capturedData = null;

      // Create mock BitmapText object to capture data
      const BitmapText = {
        registerMetrics: function(idString, data) {
          capturedIdString = idString;
          capturedData = data;
        },
        r: function(densityOrIdString, fontFamilyOrData, styleIdx, weightIdx, size, data) {
          // TIER 6b: Support both old string format and new multi-parameter format
          if (arguments.length === 2) {
            // Old format: r(idString, data)
            capturedIdString = densityOrIdString;
            capturedData = fontFamilyOrData;
          } else if (arguments.length === 6) {
            // New multi-parameter format: r(density, fontFamily, styleIdx, weightIdx, size, data)
            const density = densityOrIdString;
            const fontFamily = fontFamilyOrData;

            // Reconstruct full ID string from parameters
            // Convert numeric indices back to strings
            const styleStr = styleIdx === 0 ? 'normal' : (styleIdx === 1 ? 'italic' : 'oblique');
            const weightStr = weightIdx === 0 ? 'normal' : (weightIdx === 1 ? 'bold' : String(weightIdx));

            // Parse density and size to handle both integer and decimal formats
            const densityParts = String(density).split('.');
            const densityInt = densityParts[0];
            const densityFrac = densityParts[1] || '0';

            const sizeParts = String(size).split('.');
            const sizeInt = sizeParts[0];
            const sizeFrac = sizeParts[1] || '0';

            // Reconstruct full ID: density-{d}-{frac}-{family}-style-{style}-weight-{weight}-size-{s}-{frac}
            capturedIdString = `density-${densityInt}-${densityFrac}-${fontFamily}-style-${styleStr}-weight-${weightStr}-size-${sizeInt}-${sizeFrac}`;
            capturedData = data;
          } else {
            throw new Error(`Unexpected parameter count: ${arguments.length}`);
          }
        }
      };

      // Evaluate the file to trigger registerMetrics/r call
      eval(content);

      if (!capturedData) {
        throw new Error('Failed to extract metricsData from file (registerMetrics/r not called)');
      }

      // TIER 6: Decompress ID if it's in compressed format
      if (capturedIdString.includes(',')) {
        // Compressed format - decompress it
        capturedIdString = MetricsMinifier.decompressFontID(capturedIdString);
      }

      // Calculate original size
      const originalSize = JSON.stringify(capturedData).length;

      // Run minification with automatic roundtrip verification
      // This calls MetricsMinifier.minifyWithVerification() which:
      // 1. Minifies the data
      // 2. Expands it back using MetricsExpander
      // 3. Compares with original using deep-equal
      // 4. Throws error if mismatch
      // 5. Returns minified data on success
      const minified = MetricsMinifier.minifyWithVerification(capturedData);

      // Calculate minified size
      const minifiedSize = JSON.stringify(minified).length;
      const reduction = ((1 - minifiedSize / originalSize) * 100).toFixed(1);
      const savedBytes = originalSize - minifiedSize;

      // Generate output filename
      // Input:  metrics-density-1-0-Arial-style-normal-weight-normal-size-18-0-full.js
      // Output: metrics-density-1-0-Arial-style-normal-weight-normal-size-18-0-full-minified.js
      const baseFilename = filename.replace('-full.js', '');
      const outputFilename = `${baseFilename}-full-minified.js`;
      const outputPath = path.join(fontAssetsDir, outputFilename);

      // TIER 6b: Decompose font ID for multi-parameter format
      const parts = capturedIdString.split('-');
      const density = parts[1] + (parts[2] === '0' ? '' : '.' + parts[2]); // "1" or "1.5"
      const fontFamilyFromID = parts[3];
      const styleFromID = parts[5]; // "normal", "italic", "oblique"
      const weightFromID = parts[7]; // "normal", "bold", or numeric
      const sizeStr = parts[9] + (parts[10] === '0' ? '' : '.' + parts[10]); // "18" or "18.5"

      // Compress style and weight to indices
      const styleIdx = styleFromID === 'normal' ? 0 : (styleFromID === 'italic' ? 1 : 2);
      const weightIdx = weightFromID === 'normal' ? 0 : (weightFromID === 'bold' ? 1 : weightFromID);

      // Write minified version with TIER 7 production wrapper
      // TIER 6b: Use 'r' shorthand with multi-parameter format
      // TIER 7: Remove safety checks - assume BitmapText exists (private library, saves ~46 bytes)
      // Must match: BitmapText.r(1,'Arial',0,0,18,[...])
      const jsContent = `BitmapText.r(${density},'${fontFamilyFromID}',${styleIdx},${weightIdx},${sizeStr},${JSON.stringify(minified)})`;
      fs.writeFileSync(outputPath, jsContent, 'utf8');

      // Optional: Verify exact match with production file
      let exactMatch = null;
      if (options.verifyExact) {
        // Find corresponding production file (without -full suffix)
        const productionFilename = filename.replace('-full.js', '.js');
        const productionPath = path.join(productionDir, productionFilename);

        if (fs.existsSync(productionPath)) {
          const productionContent = fs.readFileSync(productionPath, 'utf8');
          exactMatch = (jsContent === productionContent);
        } else {
          exactMatch = 'no-production-file';
        }
      }

      results.push({
        input: filename,
        output: outputFilename,
        originalSize,
        minifiedSize,
        reduction,
        savedBytes,
        exactMatch,
        status: 'success'
      });

      console.log(`✅ ${filename}`);
      console.log(`   → ${outputFilename}`);
      console.log(`   ID: ${capturedIdString}`);
      console.log(`   Original: ${originalSize.toLocaleString()} chars`);
      console.log(`   Minified: ${minifiedSize.toLocaleString()} chars`);
      console.log(`   Saved: ${savedBytes.toLocaleString()} chars (${reduction}% reduction)`);
      console.log(`   ✓ Roundtrip verification passed`);

      if (options.verifyExact) {
        if (exactMatch === true) {
          console.log(`   ✓ Exact match with production file`);
        } else if (exactMatch === false) {
          console.log(`   ⚠️  Output differs from production file`);
        } else if (exactMatch === 'no-production-file') {
          console.log(`   ℹ️  No production file to compare (${filename.replace('-full.js', '.js')} not found)`);
        }
      }

      console.log('');

      successCount++;

    } catch (error) {
      results.push({
        input: filename,
        status: 'error',
        error: error.message
      });

      console.error(`❌ ${filename}`);
      console.error(`   Error: ${error.message}`);
      if (error.stack) {
        // Show first few lines of stack for debugging
        const stackLines = error.stack.split('\n').slice(0, 3).join('\n');
        console.error(`   Stack: ${stackLines}`);
      }
      console.error('');

      errorCount++;
    }
  }

  // Print summary
  console.log('═'.repeat(60));
  console.log(`📊 Summary: ${successCount} successful, ${errorCount} error(s)`);
  console.log('═'.repeat(60));

  if (successCount > 0) {
    console.log('\n✅ Successfully minified files:');
    const successResults = results.filter(r => r.status === 'success');

    // Calculate totals
    let totalOriginal = 0;
    let totalMinified = 0;

    successResults.forEach(r => {
      totalOriginal += r.originalSize;
      totalMinified += r.minifiedSize;
      console.log(`   ${r.output}`);
      console.log(`     ${r.originalSize.toLocaleString()} → ${r.minifiedSize.toLocaleString()} chars (${r.reduction}% reduction)`);
    });

    const totalSaved = totalOriginal - totalMinified;
    const totalReduction = ((1 - totalMinified / totalOriginal) * 100).toFixed(1);

    console.log('');
    console.log(`   Total: ${totalOriginal.toLocaleString()} → ${totalMinified.toLocaleString()} chars`);
    console.log(`   Saved: ${totalSaved.toLocaleString()} chars (${totalReduction}% overall reduction)`);

    // Report exact match results if verification was enabled
    if (options.verifyExact) {
      const exactMatches = successResults.filter(r => r.exactMatch === true).length;
      const mismatches = successResults.filter(r => r.exactMatch === false).length;
      const noProductionFile = successResults.filter(r => r.exactMatch === 'no-production-file').length;

      console.log('');
      console.log('🔍 Exact Verification Results:');
      if (exactMatches > 0) {
        console.log(`   ✓ ${exactMatches} file(s) match production exactly`);
      }
      if (mismatches > 0) {
        console.log(`   ⚠️  ${mismatches} file(s) differ from production`);
      }
      if (noProductionFile > 0) {
        console.log(`   ℹ️  ${noProductionFile} file(s) have no production file to compare`);
      }
    }
  }

  if (errorCount > 0) {
    console.log('\n❌ Errors:');
    results.filter(r => r.status === 'error').forEach(r => {
      console.log(`   ${r.input}: ${r.error}`);
    });
  }

  console.log('\n💡 Output files can be used to test different minification strategies');
  console.log('   by modifying MetricsMinifier.js and rebuilding this tool.');
  console.log('');
  if (!options.verifyExact) {
    console.log('   Tip: Use --verify-exact to compare with production files');
    console.log('   (useful for validating the tool produces identical output).');
    console.log('');
  }

  process.exit(errorCount > 0 ? 1 : 0);
}

// Run main function
processFullMetricsFiles();

EOF

# Make the output file executable
chmod +x "$OUTPUT_FILE"

# Calculate file stats
FILE_SIZE=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
LINE_COUNT=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')
FILE_SIZE_KB=$(echo "scale=1; $FILE_SIZE / 1024" | bc)

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Build completed successfully! ✅"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Output: $OUTPUT_FILE"
echo "Size: ${FILE_SIZE_KB}KB (${FILE_SIZE} bytes)"
echo "Lines: $LINE_COUNT"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Usage:"
echo "  $OUTPUT_FILE"
echo "  # or"
echo "  node $OUTPUT_FILE"
echo ""
echo "This tool will:"
echo "  1. Find all *-full.js files in font-assets/"
echo "  2. Extract full metricsData from each file"
echo "  3. Run MetricsMinifier.minifyWithVerification()"
echo "     - Minifies data (Tier 3-5 optimizations)"
echo "     - Expands back using MetricsExpander"
echo "     - Compares with original (roundtrip verification)"
echo "     - Throws error if mismatch detected"
echo "  4. Output minified .js files (EXACT production format)"
echo "  5. Report statistics and verification results"
echo ""
echo "To rebuild this tool:"
echo "  ./scripts/build-metrics-minifier.sh"
echo ""
